### PR TITLE
[HIGH] Method _transferERC721s() doesn't support Smart Accounts

### PR DESCRIPTION
**Pull request by cpp-phoenix**
## Summary
Then method `Auctions._transferERC721s()` is called by the auction winner to claim the NFT. while it uses `transferFrom()` instead of` safeTransferFrom()`. In case the winner account is a smart account his NFTs will be stuck in his account.

## Impact
The winner will lose all his NFTs if he is using a smart account to participate in the auction.

## Mitigation
Use `erc721Contract.safeTransferFrom()` as this call checks if the receiver support NFTs and if the call reverts then allow the winner to setup a different wallet to claim rewards. 
``` solidity
function updateWinnerWallet(uint256 auctionId, address newWinner) external {
    Auction storage auction = auctions[auctionId];

    if (auction.status != Status.Active) revert InvalidStatus();
    if (block.timestamp < auction.endTime) revert AuctionNotEnded();
    if (msg.sender != auction.highestBidder && msg.sender != owner()) revert NotHighestBidder();
    
    auction.highestBidder = newWinner;
}
```

### CODE REVIEW

**Comment by netdragonx** [comment]
Hmm... interesting. I've always used transferFrom for gas reasons. Can you give me an example smart account where this would actually cause a problem? I'm open to the idea that this could be an issue as we move towards smart accounts being far more common, though I don't know if it would be a major problem today.

**Comment by cpp-phoenix** [comment]
The EoA can interact with NFTs, They can approve and transfer their NFTs. But the smart account need to implement IERC721Receiver and IERC1155Receiver to support NFTs. The safeTransfer method in ERC721 and ERC1155 ensures that the received either is EoA or is IERC721Receiver and IERC1155Receiver depending upon the NFT type.

If you check the implementation of `_safeTransfer()`. It checks if the destination has implemented this method or not. The implementation can be the smart account can transfer the NFT to account owner or can support approve and transfer method for owner to transfer the NFTs freely. Otherwise the NFT will be stuck in the smart account.
```
function _safeTransfer(address from, address to, uint256 tokenId, bytes memory data) internal virtual {
    _transfer(from, to, tokenId);
    require(_checkOnERC721Received(from, to, tokenId, data), "ERC721: transfer to non ERC721Receiver implementer");
}   
```

**Comment by cpp-phoenix** [comment]
There are a lot of smart account wallets in the market that doesn't specify the support for NFTs. For eg: Gnosis safe supports NFTs but Brahma (https://www.brahma.fi/) is built on top of it but doesn't support NFTs.

It's better to check first and revert the transaction than to assume that the receiver supports NFTs

**Comment by netdragonx** [comment]
I'm not completely opposed to the change, in case there are current or future edge cases out there, but since it is a requirement to burn bid tickets to bid, it is almost guaranteed that the wallet supports NFTs: BidTicket is an ERC1155P contract, and all ERC1155P transfer options are safe transfers, so if you tried to send a smart account (that didn't support NFTs) a bid ticket, it would fail.

**Comment by cpp-phoenix** [comment]
The onERC1155Received checks that the ERC1155 is supported but it doesn't ensure the support for ERC721 NFTs too. We can assume that if a smart wallet support NFTs it'll support both. But I suggest to do the change so as the ERC721 and ERC721A NFTs are generally high in value in Eth ecosystem and we wouldn't wanna risk the loss of such NFTs.

**Pull request closed without merging**
